project-key: DSB

name: dsb_journal
tags: [starter, unet, bce]


metric:
  channel: 'Final Validation Score'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
#  meta_dir: /mnt/ml-team/dsb_2018/files
#  data_dir: /mnt/ml-team/dsb_2018/data
#  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
#  experiment_dir: /mnt/ml-team/dsb_2018/kuba/trained_pipelines/loader_test_pipeline
  # Local Environment
  meta_dir: /mnt/ml-team/dsb_2018/files
  data_dir: /mnt/ml-team/dsb_2018/data
  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
  experiment_dir: /mnt/ml-team/dsb_2018/kuba/trained_pipelines/unet_pipeline
  overwrite: 1
  num_workers: 1

  # General Params
  image_h: 128
  image_w: 128
  image_channels: 3

  # U-Net parameters
  # see also: https://arxiv.org/pdf/1505.04597.pdf
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 5

  # Training schedule
  epochs_nr: 200
  batch_size_train: 32
  batch_size_inference: 32
  lr: 0.001
  momentum: 0.9
  gamma: 0.97
  patience: 5

  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.00001
  l2_reg_dense: 0.0
  dropout_conv: 0.1
  dropout_dense: 0.0