project-key: DSB

name: dsb_journal
tags: [starter, basic, deep, bce]


metric:
  channel: 'Final Validation Score'
  goal: minimize

#Comment out if not in Cloud Environment
pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
  #data_dir:            /public/dsb_2018_data/
  #meta_dir:            /output/dsb/
  #masks_overlayed_dir: /output/dsb/masks_overlayed/
  #experiment_dir:      /output/dsb/experiments/

  # Local Environment
  data_dir: /mnt/ml-team/dsb_2018/data
  meta_dir: /mnt/ml-team/dsb_2018/files
  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
  experiment_dir: /mnt/ml-team/dsb_2018/kamil/dsb

  overwrite: 1
  num_workers: 1

  # General Params
  image_h: 128
  image_w: 128

  # Training schedule
  epochs_nr: 500
  batch_size_train: 16
  batch_size_inference: 32
  lr: 0.0005
  momentum: 0.9
  gamma: 0.97
  patience: 5

  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0001
  dropout_convo: 0.1
  dropout_dense: 0.0