project-key: DSB

name: dsb_journal
tags: [starter, unet, bce]


metric:
  channel: 'Final Validation Score'
  goal: minimize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
#  meta_dir: /mnt/ml-team/dsb_2018/files
#  data_dir: /mnt/ml-team/dsb_2018/data
#  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
#  experiment_dir: /mnt/ml-team/dsb_2018/kuba/trained_pipelines/loader_test_pipeline
  # Local Environment
  meta_dir: /mnt/ml-team/dsb_2018/files
  data_dir: /mnt/ml-team/dsb_2018/data
  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
  experiment_dir: /mnt/ml-team/dsb_2018/kuba/trained_pipelines/unet_pipeline
  overwrite: 1
  num_workers: 1

  # General Params
  image_h: 128
  image_w: 128

  # U-Net parameters
  # see also: https://arxiv.org/pdf/1505.04597.pdf
  image_width: 256
  image_height: 256
  kernel: 3
  stride: 1
  padding: 0
  nonlinearity: 'relu'
  repeat_blocks: 5
  n_filters: 64
  batch_norm: 0  # 0 or 1
  dropout: 0.3   # interval (0.0; 1.0)

  # Copied implementation
  num_classes: 2
  in_channels: 3
  depth: 5

  # Training schedule
  epochs_nr: 100
  batch_size_train: 32
  batch_size_inference: 32
  lr: 0.0001
  momentum: 0.9
  gamma: 0.97
  patience: 5

  # Regularization
  use_batch_norm: 1
  l2_reg_convo: 0.0001
  l2_reg_dense: 0.0001
  dropout_convo: 0.1
  dropout_dense: 0.0