project: piotrtarasiewicz/data-science-bowl-2018

name: data-science-bowl-2018
tags: [solution_2]

metric:
  channel: 'Final Validation Score'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - devbook.ipynb
  - morphological_postprocessing.ipynb

parameters:
# Cloud Environment
#  data_dir:                        /public/dsb_2018_data/
#  meta_dir:                        /public/dsb_2018_data/
#  masks_overlayed_dir:             /public/dsb_2018_data/masks_overlayed/
#  contours_overlayed_dir:          /public/dsb_2018_data/contours_overlayed/
#  contours_touching_overlayed_dir: /public/dsb_2018_data/contours_touching_overlayed/
#  centers_overlayed_dir:           /public/dsb_2018_data/centers_overlayed/
#  experiment_dir:                  /output/dsb/experiments/

# Local Environment
  data_dir:                        /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/data/
  meta_dir:                        /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/files/
  masks_overlayed_dir:             /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/files/masks_overlayed/
  cut_masks_dir:                   /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/files/cut_masks/
  masks_with_borders_dir:          /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/files/masks_with_borders_new/
  experiment_dir:                  /mnt/ml-team/minerva/open-solutions/data-science-bowl-2018/piotr/experiments/borders_new_memory/

  overwrite: 1
  num_workers: 4
  num_threads: 4
  image_source: memory
  pin_memory: 1
  loader_mode: crop_and_pad
  pad_method: symmetric

# General Params
  image_h: 256
  image_w: 256
  image_channels: 3

# U-Net parameters
  unet_output_channels: 2
  unet_masks_output_channels: 2
  unet_borders_output_channels: 3
  unet_activation: 'softmax'
  unet_masks_activation: 'sigmoid'
  unet_borders_activation: 'softmax'
  encoder: ResNet152

# U-Net from scratch parameters
  nr_unet_outputs: 1
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

# Training schedule
  epochs_nr: 1000
  batch_size_train: 36
  batch_size_inference: 1
  lr: 0.0001
  momentum: 0.9
  gamma: 0.99
  patience: 100
  validation_metric_name: 'sum'
  minimize_validation_metric: 1

# Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.1
  dropout_dense: 0.0

# Postprocessing
  threshold_masks: 0.2
  threshold_seeds: 0.6
  threshold_borders: 0.2
  min_mask_size: 20
  min_seed_size: 15
  tta_aggregation_method: gmean
