project-key: DSB

name: dsb_open_solution
tags: [solution_1, unet]


metric:
  channel: 'Final Validation Score'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - devbook.ipynb

parameters:
# Cloud Environment
#  data_dir:            /public/dsb_2018_data/
#  meta_dir:            /public/dsb_2018_data/
#  masks_overlayed_dir: /public/dsb_2018_data/masks_overlayed/
#  contours_overlayed_dir: /public/dsb_2018_data/contours_overlayed/
#  centers_overlayed_dir: /public/dsb_2018_data/centers_overlayed/
#  experiment_dir:      /output/dsb/experiments/

# Local Environment
  data_dir: /mnt/ml-team/dsb_2018/data
  meta_dir: /mnt/ml-team/dsb_2018/files
  masks_overlayed_dir: /mnt/ml-team/dsb_2018/files/masks_overlayed
  contours_overlayed_dir: /mnt/ml-team/dsb_2018/files/contours_overlayed
  centers_overlayed_dir: /mnt/ml-team/dsb_2018/files/centers_overlayed
  experiment_dir: /mnt/ml-team/dsb_2018/kuba/trained_pipelines/in_memory_loader
  overwrite: 1
  num_workers: 1

  # General Params
  image_h: 128
  image_w: 128
  image_channels: 3

  # U-Net parameters
  # see: https://arxiv.org/pdf/1505.04597.pdf
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 5

  # Training schedule
  epochs_nr: 1000
  batch_size_train: 32
  batch_size_inference: 32
  lr: 0.0005
  momentum: 0.9
  gamma: 0.99
  patience: 20

  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.15
  dropout_dense: 0.0

  # Postprocessing
  min_nuclei_size: 20