project: Data-Science-Bowl

name: dsb_open_solution
tags: [solution_4, unet-multitask, touching_edges]

metric:
  channel: 'Final Validation Score'
  goal: maximize

#Comment out if not in Cloud Environment
pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - devbook.ipynb
  - morphological_postprocessing.ipynb

parameters:
# Cloud Environment
  data_dir:                        /public/dsb_2018_data/
  meta_dir:                        /public/dsb_2018_data/
  masks_overlayed_dir:             /public/dsb_2018_data/masks_overlayed/
  cut_masks_dir:                   /public/dsb_2018_data/cut_masks/
  masks_with_borders_dir:          /public/dsb_2018_data/masks_with_borders/
  experiment_dir:                  /output/dsb/experiments/

# Local Environment
#  data_dir:                        /path/to/data
#  meta_dir:                        /path/to/data
#  masks_overlayed_dir:             /path/to/masks_overlayed
#  cut_masks_dir:                   /path/to/cut_masks
#  masks_with_borders_dir:          /path/to/masks_with_borders/
#  experiment_dir:                  /path/to/work/dir

  overwrite: 1
  num_workers: 4
  load_in_memory: 1
  pin_memory: 1

# General Params
  image_h: 512
  image_w: 512
  image_channels: 3

# U-Net parameters
  unet_output_channels: 2
  unet_masks_output_channels: 2
  unet_borders_output_channels: 3
  encoder: ResNet101

# U-Net from scratch parameters
  nr_unet_outputs: 1
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

# Training schedule
  epochs_nr: 1000
  batch_size_train: 4
  batch_size_inference: 4
  lr: 0.0001
  momentum: 0.9
  gamma: 0.99
  patience: 100

# Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.1
  dropout_dense: 0.0

# Postprocessing
  threshold_masks: 0.6
  threshold_seeds: 0.3
  threshold_borders: 0.3
  min_mask_size: 20
  min_seed_size: 8
