project-key: DSB

name: dsb_open_solution
tags: [solution_5]

metric:
  channel: 'Final Validation Score'
  goal: maximize

# Comment out if not in cloud environment
pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - devbook.ipynb
  - morphological_postprocessing.ipynb

parameters:
# Cloud environment
  data_dir:                        /public/dsb_2018_data/
  meta_dir:                        /public/dsb_2018_data/
  masks_overlayed_dir:             /public/dsb_2018_data/masks_overlayed/
  contours_overlayed_dir:          /public/dsb_2018_data/contours_overlayed/
  centers_overlayed_dir:           /public/dsb_2018_data/centers_overlayed/
  experiment_dir:                  /output/dsb/experiments/

# Local environment
#  data_dir:                        /path/to/data
#  meta_dir:                        /path/to/data
#  masks_overlayed_dir:             /path/to/masks_overlayed
#  contours_overlayed_dir:          /path/to/contours_overlayed
#  centers_overlayed_dir:           /path/to/centers_overlayed
#  experiment_dir:                  /path/to/work/dir

# General parameters
  valid_category_ids: '[0, 1]'
  overwrite: 1
  num_workers: 4
  load_in_memory: 1
  pin_memory: 1

# Images parameters
  image_h: 512
  image_w: 512
  image_channels: 3

# Training schedule
  epochs_nr: 1000
  batch_size_train: 4
  batch_size_inference: 4
  lr: 0.0001
  momentum: 0.9
  gamma: 0.99
  patience: 100

# Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.1
  dropout_dense: 0.0

# Postprocessing
  threshold: 0.5
  min_nuclei_size: 20

# Multi-output U-Net parameters
  nr_unet_outputs: 3
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

# Multi-output U-Net loss weights
  # weights per target
  mask: 0.45
  contour: 0.45
  center: 0.1
  # weights for bce and dice
  bce_mask: 1.0
  dice_mask: 1.0
  bce_contour: 1.0
  dice_contour: 1.0
  bce_center: 1.0
  dice_center: 1.0
